# Generated by Django 5.2.1 on 2025-07-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0010_remove_supervisorprofile_standardised_expertise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardisedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('original_topics', models.ManyToManyField(related_name='standardised_topics', to='api.originaltopic')),
            ],
        ),
        migrations.DeleteModel(
            name='TopicMapping',
        ),
    ]
