# Generated by Django 5.2.1 on 2025-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_faculty_alter_department_school_department_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammePreferenceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('programme', models.ManyToManyField(blank=True, related_name='preference_groups', to='academics.programme')),
            ],
        ),
    ]
