# Generated by Django 5.2.1 on 2025-06-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'get_latest_by': 'start_date', 'ordering': ['-start_date']},
        ),
    ]
