# Generated by Django 5.2.1 on 2025-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_programmepreferencegroup'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='office_number',
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='preferred_programmes_first_choice',
            field=models.ManyToManyField(blank=True, related_name='supervisors_first_choice', to='academics.programmepreferencegroup'),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='preferred_programmes_second_choice',
            field=models.ManyToManyField(blank=True, related_name='supervisors_second_choice', to='academics.programmepreferencegroup'),
        ),
    ]
