# Generated by Django 5.2.1 on 2025-06-04 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_programmepreferencegroup'),
        ('users', '0002_remove_supervisorprofile_office_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='preferred_programmes_first_choice',
        ),
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='preferred_programmes_second_choice',
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='preferred_programmes_first_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors_first_choice', to='academics.programmepreferencegroup'),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='preferred_programmes_second_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors_second_choice', to='academics.programmepreferencegroup'),
        ),
    ]
