# Generated by Django 5.2.1 on 2025-06-04 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_programmepreferencegroup'),
        ('users', '0003_remove_supervisorprofile_preferred_programmes_first_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='academics.school'),
        ),
    ]
