# Generated by Django 5.2.1 on 2025-06-11 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_semester'),
        ('users', '0004_supervisorprofile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='accepting_students',
            field=models.BooleanField(default=True),
        ),
    ]
