# Generated by Django 5.2.1 on 2025-06-18 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_semester_options'),
        ('users', '0006_alter_studentprofile_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='conflicting_topics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='matching_topics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='programme_match_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.semester'),
        ),
    ]
