# Generated by Django 5.2.1 on 2025-06-25 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_semester_options'),
        ('users', '0007_studentprofile_conflicting_topics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.semester'),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='preferred_programmes_first_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors_first_choice', to='academics.programmepreferencegroup'),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='preferred_programmes_second_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors_second_choice', to='academics.programmepreferencegroup'),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisors', to='academics.school'),
        ),
    ]
