# Generated by Django 5.2.1 on 2025-07-09 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_semester_options'),
        ('users', '0008_alter_studentprofile_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatorprofile',
            name='role_scope',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.semester'),
        ),
    ]
