# Generated by Django 5.2.1 on 2025-07-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_originaltopic_standardisedtopic_delete_topicmapping'),
        ('users', '0010_remove_supervisorprofile_standardised_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='standardised_expertise',
            field=models.ManyToManyField(blank=True, related_name='supervisors', to='api.standardisedtopic'),
        ),
    ]
