# Generated by Django 5.2.1 on 2025-07-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_originaltopic_standardisedtopic_delete_topicmapping'),
        ('users', '0011_alter_supervisorprofile_standardised_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='standardised_expertise',
            field=models.ManyToManyField(blank=True, null=True, related_name='supervisors', to='api.standardisedtopic'),
        ),
    ]
