# Generated by Django 5.2.1 on 2025-07-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_originaltopic_standardisedtopic_delete_topicmapping'),
        ('users', '0012_alter_supervisorprofile_standardised_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='negative_preferences',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='positive_preferences',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='negative_preferences',
            field=models.ManyToManyField(blank=True, related_name='negative_preferences_students', to='api.standardisedtopic'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='positive_preferences',
            field=models.ManyToManyField(blank=True, related_name='positive_preferences_students', to='api.standardisedtopic'),
        ),
    ]
