# Generated by Django 5.2.1 on 2025-07-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_originaltopic_standardisedtopic_delete_topicmapping'),
        ('users', '0013_remove_studentprofile_negative_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='conflicting_topics',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='matching_topics',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='conflicting_topics',
            field=models.ManyToManyField(blank=True, related_name='conflicting_students', to='api.standardisedtopic'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='matching_topics',
            field=models.ManyToManyField(blank=True, related_name='matching_students', to='api.standardisedtopic'),
        ),
    ]
