# Generated by Django 5.2.1 on 2025-07-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_standardisedtopic_original_topics_and_more'),
        ('users', '0014_remove_studentprofile_conflicting_topics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='standardised_expertise',
            field=models.ManyToManyField(blank=True, related_name='supervisors', to='api.standardisedtopic'),
        ),
    ]
